Five sections - Inheritance
Olehqa/newskeliaauto pull request #1
Opened 2020-06-05 00:13 UTC by Olehqa

2020-06-05 14:21 UTC, iikarak requested changes

2020-06-05 14:21 UTC, iikarak commented on src/main/java/homeworks/fivesection/inheritance/Human.java
> +    public abstract String getBio();
follow ordering, first variable, constructor, only after function

2020-06-05 14:21 UTC, iikarak commented on src/main/java/homeworks/fivesection/inheritance/Employee.java
> +    public Employee(String firstName , String secondName , String profession) {
?

2020-06-05 14:21 UTC, iikarak commented on src/main/java/homeworks/fivesection/inheritance/Employee.java
> +        return String.format ( "The bio should not so long for \n , \n" , getFirstName () , getSecondName () );
be

2020-06-05 14:21 UTC, iikarak commented on src/main/java/homeworks/fivesection/inheritance/InheritanceMain.java
> +        };
try to use variable humanAbs and call function getBio

2020-06-05 14:21 UTC, iikarak commented on src/main/java/homeworks/fivesection/inheritance/Student.java
> +    private String firstName;
remove them,

2020-06-05 14:21 UTC, iikarak commented on src/main/java/homeworks/fivesection/inheritance/Student.java
> +    }
add here realization with using constructor from Human ,
super( with parameters)

2020-06-05 14:21 UTC, iikarak commented on src/main/java/homeworks/fivesection/inheritance/InheritanceMain.java
> +
add usage of getBio()

2020-06-05 14:21 UTC, iikarak commented on src/main/java/homeworks/fivesection/inheritance/Student.java
> +    private String groupName;
add log4j library

2020-06-12 14:07 UTC, iikarak requested changes

2020-06-12 14:07 UTC, iikarak commented on src/main/java/homeworks/fivesection/inheritance/AbstractHuman.java
> +    private String firstName;
update access modifier

2020-06-12 14:07 UTC, iikarak commented on src/main/java/homeworks/fivesection/inheritance/Employee.java
> +        return super.getFirstName ();
Usless unless you add some additional implementation here

2020-06-12 14:07 UTC, iikarak commented on src/main/java/homeworks/fivesection/inheritance/Employee.java
> +        return Objects.equals ( getFirstName () , other.getFirstName () ) && Objects.equals ( getLastName () , other.getLastName () );
use equals of class from variable not Objects.equals

2020-06-12 14:07 UTC, iikarak commented on src/main/java/homeworks/fivesection/stringutils/StringUtils.java
> +        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@" +
Lets do this simplier:
before dog, we have also symbols, also not less than 1, and with out some special characters; 
contains '@' domain- several symbols, not less than one, after it we should have dot, after is subdomain.

2020-06-12 14:07 UTC, iikarak commented on src/main/java/homeworks/fivesection/stringutils/StringUtils.java
> +import javax.mail.internet.AddressException;
remove this lib

2020-06-12 14:07 UTC, iikarak commented on src/main/java/homeworks/fivesection/stringutils/StringUtils.java
> +public class StringUtils {
move this class to framework

2020-09-25 02:53 UTC, Olehqa commented on pom.xml
> +    <dependencies>
REMOVE

2020-09-25 02:55 UTC, merged